version: '3.1'
volumes:
  mongodb_data:
services:
  time-logger:
    build:
      context: .
    image: time-logger:dev
    volumes:
      - ./src:/usr/src/app:cached
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://root:example@mongo:27017
      DB_NAME: time-logger
      NODE_ENV: development
  mongo:
    image: mongo
    # restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
